# Generated by Django 2.2.6 on 2019-11-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('otype', models.CharField(max_length=20)),
                ('jsontext', models.TextField()),
                ('west', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('east', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('south', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('north', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltype', models.CharField(max_length=3)),
                ('o0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_from', to='geodata.Object')),
                ('o1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_to', to='geodata.Object')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.Object')),
            ],
        ),
    ]
