# Generated by Django 2.2.6 on 2019-12-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('name', 'otype')},
        ),
    ]
