# Generated by Django 2.2.1 on 2019-06-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('jsontext', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='source',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.AddField(
            model_name='object',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.Source'),
        ),
    ]
