# Generated by Django 2.2.1 on 2019-06-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_auto_20190607_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='otype',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
    ]
