# Generated by Django 2.2.1 on 2019-06-17 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltype', models.CharField(max_length=3)),
                ('o0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_from', to='geodata.Object')),
                ('o1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_to', to='geodata.Object')),
            ],
        ),
    ]
